### ISSUE TITLE
Access /www directory

### ISSUE THREAD

**Issue by pedrotes** [tomsik68/docker-xampp#1]
please can you tell me how do i access the www directory thank you.

**Comment by tomsik68** [comment]
This is an example launch command: `docker run -p 22:41061 -p 80:41062 -d -v ~/my_web_pages/my_testing_page1:/www tomsik68/xampp`. If you run your container using this command, directory at `~/my_web_pages/my_testing_page1` will be mounted as www directory.

**Comment by pedrotes** [comment]
But i have to do it in Docker terminal not in the kitmatic right?

**Comment by pedrotes** [comment]
If i leave you my skype name do you add me so you can show me becouse i'm getting errors.
My contact name is: pedrotesmorais
My email: hardsoft@sapo.pt
Thanks

**Comment by pedrotes** [comment]
sorry for my nubbish at this but now i'm getting this error: "Cannot start container ...: failed to create endpoint thirsty_franklin on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:22: bind: address already in use".
Can you help me please?
Thank you for your time.

**Comment by tomsik68** [comment]
I'm sorry I wasn't able to get back to your issue, I'm busy with other things...  . I'm not sure if it helps, but I found some relevant issues on github:
https://github.com/nitrous-io/tug/issues/8
https://github.com/blinkreaction/drude/issues/46
https://github.com/blinkreaction/boot2docker-vagrant/issues/31
