### ISSUE TITLE
How can I access the mysql from shell?

### ISSUE THREAD

**Issue by ratulcse27** [tomsik68/docker-xampp#10]
Hi @tomsik68  can you please tell me how to access docker-xampp 's mysql from the shell? It would be a great help.

**Comment by tomsik68** [comment]
Hey, you should be able to use `mysql` cli utility on the guest machine to do so. The simplest way to get on the guest machine is to run `docker exec -ti <container name> bash` on your host. 

If you want to access mysql from host machine, you can forward mysql's default port(I think 3306) from the container and use mysql to connect to it.

**Comment by ratulcse27** [comment]
@tomsik68  I followed your instruction, but it says `bash: mysql: command not found`

**Comment by tomsik68** [comment]
Hmm you can try installing mysql in the container then `apt-get -y install mysql`

**Comment by tirjok** [comment]
@ratulcse27 Please run in your bash `export PATH=/opt/lampp/bin:$PATH`

Then you will get all of this service
