### ISSUE TITLE
Please help me how to access restricted phpmyadmin

### ISSUE THREAD

**Issue by mah-shamim** [tomsik68/docker-xampp#11]

**Comment by tomsik68** [comment]
Just navigate to `http://localhost:41062/dashboard`(replace 41062 by forwarded http port) and access phpmyadmin from there.
What's the problem?

**Comment by mah-shamim** [comment]
how to stop phpmyadmin access?

**Comment by tomsik68** [comment]
You need to configure apache to restrict access to phpmyadmin. This stackoverflow answer provides some clues how to do that: http://stackoverflow.com/a/21703042

**Comment by mah-shamim** [comment]
thanks
