### ISSUE TITLE
How can edit my php.ini file?

### ISSUE THREAD

**Issue by alperendurmus** [tomsik68/docker-xampp#17]
Hi there. 
I couldn't figure out how can I edit my php.ini file. All advices will be appreciated.

**Comment by tomsik68** [comment]
There are at least 3 ways:
1. Just use docker's `-v` flag to mount the folder where `php.ini` is located to your directory. 
2. Start bash inside docker and use nano.
3. SSH into the container and use nano: `ssh root@localhost -p 41061`.

Please not that `php.ini` is probably located somewhere inside `/opt/lampp`.

**Comment by alperendurmus** [comment]
Thank you very much!
