### ISSUE TITLE
Connect to Docker's MySQL

### ISSUE THREAD

**Issue by ndhuts** [tomsik68/docker-xampp#22]
I used Macbook Pro. After running container, I tried to connect to MySQL inside the container with Navicat as follows : 
- Host : localhost
- Port : 3306
- User Name : root
- Password  : xxx (I've changed MySQL password via phpMyAdmin from container)
But could not connect. I tried to change host to 127.0.0.1 and still didn't work.

I also tried to check container IP, and it gave me address 172.17.0.2. Changed host to that, and still didn't work.

I ran docker ps to check if 3306 is already exposed, and got this result, which I assume 3306 already opened and exposed
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                                    NAMES
ed8bf8c550e9        tomsik68/xampp      "sh /startup.sh"    45 minutes ago      Up 45 minutes       3306/tcp, 0.0.0.0:41061->22/tcp, 0.0.0.0:41062->80/tcp   myXampp

**Comment by tomsik68** [comment]
Hi, can you try browsing to http://localhost:41062/ to see if the webserver works??

**Comment by mejerome** [comment]
Can you access mysql inside the container so I can import a file.sql through Dockerfile?

**Comment by tomsik68** [comment]
> Can you access mysql inside the container so I can import a file.sql through Dockerfile?

I think so. You need to perform two modifications to your Dockerfile. First, copy `file.sql` to the container and then import it via mysql command.

You can easily copy something into the container by adding for example: `COPY file.sql /file.sql` above the following line:
https://github.com/tomsik68/docker-xampp/blob/3ab75a72b9eda7036a679b9231ea0772f1ef31f4/Dockerfile#L18

The sql import command should be appended somewhere below the following line (after xampp install):
https://github.com/tomsik68/docker-xampp/blob/3ab75a72b9eda7036a679b9231ea0772f1ef31f4/Dockerfile#L21

**Comment by tomsik68** [comment]
I'm closing the issue for now, if there's anything related you'd like to ask, feel free to reopen.
