### ISSUE TITLE
where can i pull images with PHP Version 5.6.21  ? 

### ISSUE THREAD

**Issue by phicha20224** [tomsik68/docker-xampp#27]
> Dear Mr,

I am check my app error on new container.
and it seem because of  PHP Version 8.0

please tel me how to pull version with 5.6 i check in docker hub only have tag latest...

Thank you..

**Comment by tomsik68** [comment]
Hi, I currently don't build images other than the latest xampp version. I might change that in the future, but you can fix the problem for yourself very easily as follows:

1. clone this repo
2. open the Dockerfile in your text editor and change the url for this curl command: https://github.com/tomsik68/docker-xampp/blob/0d0b77db8965b750197fa2ee27fb1e08aaf6a537/Dockerfile#L18
to this:  `https://www.apachefriends.org/xampp-files/5.6.28/xampp-linux-x64-5.6.28-0-installer.run`
3. run `docker build .` from the repo directory

Feel free to ask any additional questions you might have :smile:

**Comment by phicha20224** [comment]
Thank You Mr,

**Comment by tomsik68** [comment]
Images using PHP 5,7 and 8 are now built automatically and pushed by tags.
You can use `tomsik68/docker-xampp:5` or `tomsik68/docker-xampp:5.6.28`.

**Comment by princeshahriar007** [comment]
@tomsik68 could you please give me access to tomsik68/docker-xampp:5 or tomsik68/docker-xampp:5.6.28 . It is asking for access

**Comment by tomsik68** [comment]
Hi, the image is currently unavailable because of #30, so I closed this issue prematurely.

**Comment by princeshahriar007** [comment]
> Hi, the image is currently unavailable because of #30, so I closed this issue prematurely.

Thanks for your support. I did build the image manually following your instruction using xampp:5.6.40 and it did not stuck at installation.

One more thing I want to know How can I bypass the  http://localhost:41062/www/ address to http://localhost:41062/ Because I have an old prestashop site that uses the root directory so I can't use it under the www subdirectory. Could you please tell me how can I do that?

**Comment by tomsik68** [comment]
> Thanks for your support. I did build the image manually following your instruction using xampp:5.6.40 and it did not stuck at installation.

Thank you for looking into this! This helps a lot. I'm closing this issue, let's continue the discussion about root directory in #31 :smile:
