### ISSUE TITLE
How do I expose my app under / instead of /www?

### ISSUE THREAD

**Issue by tomsik68** [tomsik68/docker-xampp#31]
How can I bypass the  http://localhost:41062/www/ address to http://localhost:41062/ Because I have an old prestashop site that uses the root directory so I can't use it under the www subdirectory. Could you please tell me how can I do that?

_Originally posted by @princeshahriar007 in https://github.com/tomsik68/docker-xampp/issues/27#issuecomment-787936427_

**Comment by tomsik68** [comment]
I just tested this and mounting your app folder to `/opt/lampp/htdocs/` works just fine. Just run your container like this:
`docker run -p 41062:80 -d -v ~/my_web_pages:/opt/lampp/htdocs/ tomsik68/xampp:5`

The only change is that `~/my_web_pages` is mounted to `/opt/lampp/htdocs/` instead of `/www`

**Comment by princeshahriar007** [comment]
Thanks, I just checked and tested in the /opt/lampp/htdocs directory as well

Thank you so much
