### ISSUE TITLE
Container not running for different Xampp

### ISSUE THREAD

**Issue by vikaskhunteta** [tomsik68/docker-xampp#34]
Hello Tom,

Thanks for creating this xampp image, I have been trying to create another image by cloning this repo, I did what is suggested into readme my Xampp server is not starting.

I used this installer `https://sourceforge.net/projects/xampp/files/XAMPP%20Linux/7.2.34/ `

getting these logs

```
not recognized
For help, use /usr/bin/supervisord -h

Unknown command or add-on!
```

I don't know how to fix it because I am new to Docker

For default git repo the Xampp is working fine

Any suggestion would be helpful

**Comment by tomsik68** [comment]
Hi Vikas, I'm sorry for the delay. It could be that the particular XAMPP version has issues with the installer. Could you please try using a different one? Btw I also build this image for php version 7 - just pull tag `7` like this:
```bash
docker run --name myXampp -p 41061:22 -p 41062:80 -d -v ~/my_web_pages:/www tomsik68/xampp:7
```

It should be sufficient.

**Comment by tomsik68** [comment]
Github action now builds images for php versions 5,7 and 8. I believe this wasn't issue of the docker image, but the xampp installer. 

Feel free to re-open if there are any further concerns.
