### ISSUE TITLE
Error when mount Mysql data with docker-compose

### ISSUE THREAD

**Issue by martinCabo** [tomsik68/docker-xampp#35]
I am trying to create a volume to persist my Mysql data, but it produces an error when start **only in windows host**, On mac it works fine. 

My docker-compose.yml is:
_version: '3'
services:
    myContainer:
        container_name: containerName
        build: ./DockerFile
        ports:
            - "81:81"
            - "41061:22"
        volumes:
            - "path/to/code:/opt/lampp/htdocs/project"
            - "./DockerFile/mysql/data:/opt/lampp/var/mysql_"
          

I found the error at mysql log, and it says:

"Can't start server : Bind on unix socket: Input/output error
2021-08-10 18:20:19 140245831134080 [ERROR] Do you already have another mysqld server running on socket: /opt/lampp/var/mysql/mysql.sock ?
2021-08-10 18:20:19 140245831134080 [ERROR] Aborting

2021-08-10 18:20:21 130 mysqld_safe mysqld from pid file /opt/lampp/var/mysql/60f034929146.pid ended"

I dont know why it's happening (And I even  didn't found any place who can give me a light), and if you can help, it would be great.
Keep in contact, and really thanks you!

**Comment by tomsik68** [comment]
Looks like you're mounting the whole mysql directory. I might be just shooting in the dark, but mysql directory might be the place where the unix socket for mysqld is created, so if you mount it on Mac socket is created just fine. However, if you mount it on windows, windows has no support for special socket files, so it throws an error.

If all you need is persistence, you can specify a volume without a mountpoint. I imagine that should help.
See [docker documentation](https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose) for more information.

**Comment by martinCabo** [comment]
Thank you very much for your answer, I will try that... may be is the solution. 

Best Regards!

**Comment by tomsik68** [comment]
I'm closing this issue for now, feel free to re-open if you have any further questions.
