### ISSUE TITLE
XAMPP Control panel

### ISSUE THREAD

**Issue by josejuanmayorga** [tomsik68/docker-xampp#37]
Hi tomsik68, Merry Christmas.
I hope to find you having the best time with your family and friends.
I am having a good time with your XAMPP docker, it is helping me to work with my examples.
I can access to www folder to load my php exercises and xampp and phpmyadmin pages but I do not know how to load XAMPP Control panel.
Could you tell me how to get access to that page in this docker?
Thank you very much for your help and support.
Happy new year.
José.

**Comment by tomsik68** [comment]
Hello José!

Assuming you used this command I provided to start the container:

```bash
docker run --name myXampp -p 41061:22 -p 41062:80 -d -v ~/my_web_pages:/www tomsik68/xampp
```

You should be able to access the XAMPP control panel at [http://localhost:41062/xampp](http://localhost:41062/xampp). Let me know if that doesn't work.

Merry Christmas and happy new year!

**Comment by josejuanmayorga** [comment]
Hi tomsik68, thank you very much for such rapid answer.
I am very please..
Yes, I am using that command you provided to start the container.
And I got loaded a page using the link you indicated but it is not like this one:
![image](https://user-images.githubusercontent.com/87968330/147413983-c4296b1b-8d5b-4c15-91ca-306bd7e7e12e.png)
Am I doing something wrong?
Perhaps, I am understanding the concepts wrongly?
Sorry, I am just starting to program in back-end.

**Comment by tomsik68** [comment]
The screenshot you sent seems to use XAMPP on Windows. This container runs in docker, so it uses XAMPP on Linux which doesn't have such a GUI. To get the same functionality, you can start a terminal in your docker container (`docker exec -ti myXampp bash`) and do everything from there:

1. restart all services: `/opt/lampp/lampp restart`
2. view config files: `cd /opt/lampp/apache2/conf.d/ && ls`
3. netstat: `netstat`
etc.

I don't think you can access that control panel when running XAMPP in docker.

**Comment by josejuanmayorga** [comment]
Hi tom.
As I said, I am total newbily.
Thank you very much for your interest and explanation.
Merry christmas and Happy new year.
José.

**Comment by tomsik68** [comment]
I'm closing this issue for now, feel free to re-open if you have any further questions.
