### ISSUE TITLE
XAMPP new security concept

### ISSUE THREAD

**Issue by tomsik68** [tomsik68/docker-xampp#4]
Admin can't connect to `/phpmyadmin` unless `httpd-xampp.conf` is modified.
`    Require all granted` is required for both phpmyadmin and phpsqliteadmin.

**Comment by tomsik68** [comment]
There's an issue with the file `/opt/lampp/etc/extra/httpd-xampp.conf`.
If any1 encounters the xampp 403 error message on phpmyadmin or phpsqliteadmin, just run this command in the container: `sed -i.bak s'/Require local/Require all granted/g' /opt/lampp/etc/extra/httpd-extra.conf`

**Comment by S-Kazuki** [comment]
@tomsik68 
There seems to be an small error.
`sed -i.bak s'/Require local/Require all granted/g' /opt/lampp/etc/extra/httpd-extra.conf`
=>
`sed -i.bak s'/Require local/Require all granted/g' /opt/lampp/etc/extra/httpd-xampp.conf`
thank you.

**Comment by tomsik68** [comment]
@S-Kazuki Thanks! I couldn't figure out why it didn't work when I added it to the Dockerfile :D
