### ISSUE TITLE
how to install "ixed.8.1.lin" loader from the SourceGuardian site

### ISSUE THREAD

**Issue by alizarei22** [tomsik68/docker-xampp#47]
Hello,

I'm running Docker on **Linux**. I use the following command to start the container:

```bash
docker run --name myXampp -p 41061:22 -p 41062:80 -d -v ~/my_web_pages:/www tomsik68/xampp:8
```

I want to install "ixed.8.1.lin" that requires a SourceGuardian loader.
I have "ixed.8.1.lin" installation file and i should install it in /opt/lampp/lib/php/extensions/no-debug-non-zts-20210902 directories and after that i edit /opt/lampp/etc/php.ini and add 'extension=ixed.8.1.lin' directive.
my problem is i can not find "/opt/lampp/lib/php/extensions/no-debug-non-zts-20210902" and "/opt/lampp/etc/php.ini" in my system.
can you help me?

Thank you!

**Comment by tomsik68** [comment]
Hi, I don't have any experience with SourceGuardian, so I can only guess. I recommend you build your own Dockerfile with the SourceGuardian loader. You should be able to start with this:

```dockerfile
FROM tomsik68/xampp:5   # feel free to change the XAMPP/PHP version
RUN # SourceGuardian install commands
```

Where SourceGuardian install commands come from this page: https://serverpilot.io/docs/how-to-install-source-guardian/

**Comment by alizarei22** [comment]
Thank you for your suggestion, I will definitely test this method
good luck!
