### ISSUE TITLE
Unknown command or add-on

### ISSUE THREAD

**Issue by mkiszka** [tomsik68/docker-xampp#48]
# Bug Report

I'm running Docker on: 

- Windows 11 as a Docker host
- git with core.autocrlf = true (checkout Windows style)

I'm not sure if it's global problem or only mine.

## Actual behavior

After building the Dockerfile and running the container, I encountered a problem. The container starts with the error:

`Unknown command or add-on! 
   not recognized
For help, use /usr/bin/supervisord -h`

This was because the Ubuntu shell has a problem with Windows-style line endings in scripts.

## Expected behavior

Running without any error

## Fix 1:
- force checkout with unix-style line endings even on Windows by using .gitattributes

## Fix 2:
- change line ending style after coping startup.sh from host to docker image

I will create PR with Fix 1 for a moment.

**Comment by tomsik68** [comment]
Thank you for reporting this! I merged your fix. Let me know if there's anything else that needs to change for this issue.

**Comment by mkiszka** [comment]
Now, everything's ok. Thanks.
