### ISSUE TITLE
So, Apache and MySQL is not under control of supervisor, isn't it?

### ISSUE THREAD

**Issue by yanhuixie** [tomsik68/docker-xampp#5]
I'm just worried about how Apache and MySQL can properly save the data and status then exit.

**Comment by tomsik68** [comment]
LAMP is not under control of supervisor.
I didn't actually test data persistence between individual container runs. I think it depends on the way you stopped `lampp` - there might be difference between using `lampp stop` and `docker stop`. I'm not sure myself, so if you did any tests on this and/or noticed data loss, please report it here :)

I'd also like to point out, that this container is **not** meant to be used with production setups, as it uses (probably) the **worst** security practices, so developers can work (in most cases) without worrying about web server configuration.

**Comment by yanhuixie** [comment]
Hi @tomsik68 ! Thanks for your confirmation. I have just spent some time dig into this problem. I found out that it should be too hard to make lampp controlled under supervisor, because mysql and apache which shipped by lampp is run as daemon, but supervisor requires NODAEMON. Your docker image is good enough as a development environment. :-)
