### ISSUE TITLE
Mount existing db to container

### ISSUE THREAD

**Issue by ydrob** [tomsik68/docker-xampp#56]
Hello,

Can I mount existing db from host to docker container? I want to do it to save all data on my host, even if I recreate a container.

Thank you!

**Comment by tomsik68** [comment]
Hi ydrob, can you try looking at this question? https://github.com/tomsik68/docker-xampp/issues/39

Let me know if it helps or not.

**Comment by ydrob** [comment]
Thank for answer, I use another way, I modified your image and create backup of database using cron and place it to mounted folder, it suits me.
