### ISSUE TITLE
Add 8.3.6

### ISSUE THREAD

**Issue by bonelifer** [tomsik68/docker-xampp#61]
**Is your feature request related to a problem? Please describe.**
Add php 8.3.6.

**Comment by tomsik68** [comment]
Hey, I'll be happy to build a container with PHP 8.3.6 once it's available as a part of XAMPP. Currently, the latest version offerred by XAMPP is 8.2.12. Would that version work for you?

**Comment by bonelifer** [comment]
You can ignore this. I ended up going with https://github.com/creed1120/php-docker
