### ISSUE TITLE
cant remap ports to container

### ISSUE THREAD

**Issue by jmcnamara10001** [tomsik68/docker-xampp#62]
Hello,

I'm running Docker on **Linux**. I use the following command to start the container:

```bash
# docker run -it --name pj10 -p 41062:80 -d -v ~/my_web_pages:/www -v ~/my_apache_conf:/opt/lampp/apache2/conf tomsik68/xampp
docker: Error response from daemon: Conflict. The container name "/pj10" is already in use by container "bf11189421643442aac25205b9532cc19c16a05d0b6f90ce63bdbf9163b2d4a3". You have to remove (or rename) that container to be able to reuse that name.

i kept getting rename container or remove container already in use.

then i try to rename or stop or any scenario but i cant get it to start with 
docker run with the correct paremeters afterwards

please help thanks


Thank you!

**Comment by jmcnamara10001** [comment]
hi--

i needed to set up a volume and commit it with autostart processes. thanks

**Comment by tomsik68** [comment]
Hello,

it seems like there is a naming conflict. To resolve this, we need to come up with a container name that isn't used on your machine. Can you please share the list containers you have on your machine? You can use the following command to list them:

```bash
docker ps -a
```

**Comment by jmcnamara10001** [comment]
Hi Tomisk68-

Im doing better with docker right now. Sorry i forgot to update. I needed to learn Dockerfile, volume, init.sh, and compose.yaml. The services need to be autostarted. Then there wont be this issue.

thanks,
jim

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by tomsik68** [comment]
I'm glad to hear you made some progress. I'm closing this issue for now, feel free to reopen if you have any additional questions.
