### ISSUE TITLE
Path Problem

### ISSUE THREAD

**Issue by romallie0214** [tomsik68/docker-xampp#65]
having path problem in my project "/dist/css/adminlte.css"  cannot be recognized

**Comment by tomsik68** [comment]
Hey, thank you for reaching out! Can you please clarify which program is reporting this error message? At first glance, it seems like a frontend problem reported by your web browser which can be resolved by changing the path to something else. Perhaps `/www/dist/css/adminlte.css` could work better?

**Comment by romallie0214** [comment]
It works!

**Comment by tomsik68** [comment]
I'm glad you were able to get this to work :tada:
